tasks:
  - init: |
      docker-compose pull
  - command: |
      docker-compose up

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: false
    addComment: false
    addBadge: true

# ports:
#   - port: 5432
#     onOpen: ignore
#   - port: 8088
#     onOpen: ignore



